### ISSUE TITLE
Failed project

### ISSUE THREAD

**Issue by DevKumar00001** [Siddhesh2377/AndroidBox#1]
Bro Your project is not compiling and you didn't provided any app for test and you have not setp up cli so we can do something.Please fix the problems else no one will able to contribute.

**Comment by TechnicalStudioDeveloper** [comment]
Also add discussion section there

**Comment by Siddhesh2377** [comment]
Thanks for the report, actually I am new to GitHub so, i will Lear more about it, an as for the Alpha release it is coming soon

**Comment by TechnicalStudioDeveloper** [comment]
> 

Plz check if you can fix this error of your project: https://github.com/TechnicalStudioDeveloper/AndroidBox/actions/runs/4905118944/jobs/8758694580#step:5:10

**Comment by Siddhesh2377** [comment]
I will update the repo in between 2 days

**Comment by TechnicalStudioDeveloper** [comment]
> I will update the repo in between 2 days

Please enable discussion will help to contact inspite of creating issues.

**Comment by Siddhesh2377** [comment]
Done

**Comment by TechnicalStudioDeveloper** [comment]
> Done

And what about GitHub workflow and gradle errors

**Comment by Siddhesh2377** [comment]
Bro, actually the thing is i am a little busy with My ITI so till next Saturday i can't do anything here

**Comment by Siddhesh2377** [comment]
re staring the Project
